// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFORvYd-ntfJR8jX8M5vidQ-b6Yzv9Tzo',
    appId: '1:371202474308:web:d5f96c9ef3da0ebd399711',
    messagingSenderId: '371202474308',
    projectId: 'ebookreader-609ce',
    authDomain: 'ebookreader-609ce.firebaseapp.com',
    storageBucket: 'ebookreader-609ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYrpA1wHnTVV-b63dADHatDp-pIftVRF8',
    appId: '1:371202474308:android:cc46fd23b7c91695399711',
    messagingSenderId: '371202474308',
    projectId: 'ebookreader-609ce',
    storageBucket: 'ebookreader-609ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjVnQL-idLAinRHAQmm77Q2Y2l9MrWLw0',
    appId: '1:371202474308:ios:8d22b77fb97c5c4c399711',
    messagingSenderId: '371202474308',
    projectId: 'ebookreader-609ce',
    storageBucket: 'ebookreader-609ce.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjVnQL-idLAinRHAQmm77Q2Y2l9MrWLw0',
    appId: '1:371202474308:ios:8d22b77fb97c5c4c399711',
    messagingSenderId: '371202474308',
    projectId: 'ebookreader-609ce',
    storageBucket: 'ebookreader-609ce.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFORvYd-ntfJR8jX8M5vidQ-b6Yzv9Tzo',
    appId: '1:371202474308:web:2367b4f9bfe12439399711',
    messagingSenderId: '371202474308',
    projectId: 'ebookreader-609ce',
    authDomain: 'ebookreader-609ce.firebaseapp.com',
    storageBucket: 'ebookreader-609ce.appspot.com',
  );
}
